### ISSUE TITLE
Operation System typo

### ISSUE THREAD

**Issue by codiini** [DonyaOS/Donya#1]
Is it "Operation System" or "Operating System", wanted to confirm before making changes to the readme file

**Comment by BaseMax** [comment]
Hi Iniubong, @codiini 

Thank you for your message and for reminding me of this typo mistake.

I solve typo problem.
Thanks again.

In the fact, it's a new OS. But it will be a Linux Distribution.

It's a matter of whether Linux distribution is an operating system or not. (Oops)
It depends on how we develop and how far we go in the future.

I wonder how you found this organization? **:)**
Because it has not been made public yet and it is not even ready.
Although we published various scripts for compiling the kernel and ....

Regards,

**Comment by codiini** [comment]
i'm happy to help in a small way, not sure i could write a Linux distribution OS or contribute code to it except we're talking about the website, I'm a Front end Dev.

It just showed up on my feed that you created a new repo and i decided to check it out.
I think it's really cool what your'e building.
would DonyaOS have any significant difference from other Linux Distros?

**Comment by prince-dsd** [comment]
Unlike a binary software distribution, the source code is compiled locally according to the user's preferences.

**Comment by prince-dsd** [comment]
Even the smallest contribution counts we would love to have you as a part of the community
